#------------------------------------------------------------------------------*
# Record question labels
#------------------------------------------------------------------------------*

# For Emory RedCap questionnaire
c4_labels <- c(
  "date" = "Fecha de hoy",
  "by" = "¿Quien completo el formulario?",
  "dob" = "Fecha de nacimiento del nino ",
  "age" = "Edad del nino ",
  "time" = "Hora ",
  "masimo" = "Numero de serie del equipo Masimo:",
  "con_date" = "Fecha del consentimiento de los padres o responsable legal nino:",
  "con_no" = "Numero de formulario de consentimiento de los padres o responsable legal del nino:",
  "age_24" = "A1. ¿El nino tiene menos de 24 meses?",
  "dist" = "A2. ¿El nino vive en el distrito de HAPIN?\nIndicacion: El trabajador de campo debe responder a esta pregunta segun la direccion y el mapa de HAPIN ",
  "premature" = "B1. ¿El nino nacio prematuro (antes de las 37 semanas)?",
  "defect" = "B2. ¿Alguna vez un medico le ha dicho que el nino nació con un defecto cardiaco?",
  "health_fac" = "B3. ¿Fue admitido en algun centro de salud o hospital donde paso la noche?",
  "pneumonia" = "B4. ¿Fue diagnosticado con neumonia? ",
  "anti" = "B5. ¿Recibio antibioticos? ",
  "respir" = "B6. ¿Algun sintoma respiratorio que incluya tos, sibilancias, flema, falta de aliento/aire?\nIndicacion: no incluir congestion o secrecion nasal ",
  "gastro" = "B7. ¿Algun sintoma de una enfermedad gastrointestinal?\nIndicacion: incluye diarrea, heces blandas, sangre en las heces o TRO administrado ",
  "fever" = "B8. ¿Fiebre?",
  "diff_br" = "B9. ¿Dificultad al momento de respirar?",
  "fast_br" = "B10. ¿Respiracion rapida?",
  "nose" = "B11. Rinorrea /congestion o secrecion nasal",
  "fever_curr" = "B12. ¿Fiebre?\nIndicacion: No tiene que medir la temperatura, pero queremos excluir a cualquier nino que pueda estar enfermo. Esto podria ser que la madre haya notado que el nino esta tibio o que el medico/la enfermera le ha dicho que el nino tiene fiebre. ",
  "chest" = "B13. ¿Tiraje (subcostal) del pecho?\nIndicacion: Observacion del trabajador de campo/enfermera/medico",
  "cyanosis" = "B14. ¿Cianosis?\nIndicacion: Observacion del trabajador de campo/enfermera/medico ",
  "nose_curr" = "B15. ¿Rinorrea?\nIndicacion: Observacion del trabajador de campo/enfermera/medico ",
  "age_gr" = "C1. Grupo de edad\nIndicacion: ver la edad al comienzo del formulario ",
  "sex" = "C2. Sexo del nino ",
  "oxy_60" = "C3. Saturacion de oxigeno por oximetria de pulso medida a los 60 segundos",
  "oxy_90" = "C4. Saturacion de oxigeno por oximetria de pulso - medida a los 90 segundos",
  "oxy_120" = "C5. Saturacion de oxigeno por oximetria de pulso - medida a los 120 segundos",
  "mean_oxy" = "C6. Promedio de oximetria de pulso",
  "rr1" = "C7. Promedio de frecuencia respiratoria- medida No.1\nIndicacion: RRp rpm en 60 segundos ",
  "rr2" = "C8. Promedio de frecuencia respiratoria- medida No.2\nIndicacion: RRp rpm en 120 segundos",
  "mean_rr" = "C9. Promedio de frecuencia respiratoria",
  "m_rr1" = "Frecuencia respiratoria manual- medida No.1\nIndicacion: numero de respiraciones contadas en 60 segundos ",
  "m_rr2" = "Frecuencia respiratoria manual- medida No.2\nIndicacion: numero de respiraciones contadas en 60 segundos ",
  "m_mean_rr" = "D3. Promedio de frecuencia respiratoria",
  "phase_iv_piloting_complete" = "Complete?"
)


# For GT pneumonia questionnaire
c36_labels <- c(
  "record_id" = "Record ID",
  "redcap_repeat_instrument" = "Repeat Instrument",
  "redcap_repeat_instance" = "Repeat Instance",
  "today" = "Fecha de hoy :                                 ",
  "time" = "Hora:",
  "interviewer" = "Entrevistadora:",
  "dateofbirth" = "Fecha de Nacimiento:",
  "age" = "Edad del niño:",
  "municipio" = "Municipio:",
  "com_jalapa" = "&iquestEn que comunidad de Jalapa vive usted?",
  "com_mataque" = "&iquestEn que comunidad de Mataquescuintla vive usted?",
  "com_monjas" = "&iquestEn que comunidad de Monjas vive usted?",
  "com_alzatate" = " &iquestEn que comunidad de San Carlos Alzatate vive usted?",
  "com_jilotepeque" = "&iquestEn que comunidad de San Luis Jilotepeque vive usted?",
  "com_pinula" = "&iquestEn que comunidad de San Pedro Pinula vive usted?",
  "com_chaparron" = " &iquestEn que comunidad de San Manuel Chaparron vive usted?",
  "com_otra" = "Otra comunidad:",
  "tipo_servicio" = "Tipo de servicio:",
  "a01" = "A1 - PREGUNTE: ¿el niño tiene actualmente un episodio agudo de tos?",
  "a01_1" = "A1.1 - Si la respuesta es SÍ, ¿hace cuantos días inició ese episodio agudo de tos?",
  "a02" = "A2 - PREGUNTE: ¿El niño actualmente tiene un episodio agudo de dificultad para respirar? Indicación: esto no incluye problemas para respirar debido a nariz tapada ",
  "a02_1" = "A2.1 - Si la respuesta es SÍ, ¿hace cuantos días inició ese episodio agudo de dificultad para respirar?",
  "a03" = "A3 - ¿Las respuestas A1, o A2 fueron SÍ?",
  "b01" = "B1 - PREGUNTE: ¿Quién refirió al niño a este servicio?",
  "b02" = "B2 - PREGUNTE: ¿por este episodio de Tos y/o dificultad respiratoria el niño fue hospitalizado y el médico le dijo que fue neumonía?",
  "c01" = "C1 - OBSERVE: ¿El niño presenta en este momento tiraje intercostal?",
  "c02" = "C2 - Número de serie de MASIMO",
  "c03" = "C3 - Frecuencia respiratoria MASIMO 1:",
  "c04" = "C4 - Frecuencia respiratoria MASIMO 2:",
  "c05" = "C5 - Promedio de frecuecia respiratoria (RedCAP) Ecuación: (C3 + C4) / 2 ",
  "c06" = "C6 - EVALUE: ¿tiene taquipnea de acuerdo a la edad?  Indicación: la respuesta a esta pregunta se basará en los parámetros encontrados en fase IV y la respuesta obtenida en C5. Revisar la lista de parámetros de acuerdo a edad ",
  "c07" = "C7 - EVALUE: ¿el niño llena los criterios de OMS para tener neumonía?  Indicación: las respuesta es SI en C1 o en C6 (un Sï basta) ",
  "d01" = "D1 - Saturación de oxihemoglobina a los 60 segundos",
  "d02" = "D2 - Saturación de oxihemoglobina a los 90 segundos",
  "d03" = "D3 - Saturación de oxihemoglobina a los 120 segundos",
  "d04" = "D4 - Promedio de oximetría de pulso en RedCAP Ecuación: (D1 + D2 + D3) / 3 ",
  "d05" = "D5 - ¿La medición de la saturación de oxígeno fue medida a temperatura ambiente sin oxígeno suplementario?",
  "e01" = "E1 - PREGUNTE: ¿el niño no mamá nada, o no puede tomar nada?",
  "e02" = "E2 - PREGUNTE: ¿el niño lo vomita todo?",
  "e03" = "E3 - PREGUNTE: ¿El niño ha tenido convulsiones (ataques)?",
  "e03_1" = "E3.1 - OBSERVE: ¿El niño esta convulsionado ahora?",
  "e04" = "E4 - OBSERVE: ¿Esta el niño letárgico o inconsciente?",
  "e05" = "E5 - EVALUAR CON TERMOMETRO: Fiebre INDICACIÓN: la temperatura axilar es mayor a 37.5°C ",
  "e06" = "E6 - EVALUAR CON TERMOMETRO: Hipotermia INDICACIÓN: la temperatura axilar es menor a 35.5°C ",
  "e07" = "E7 - PREGUNTE: ¿El niño está teniendo problemas para comer?",
  "e08" = "E8 - OBSERVE y ESCUCHE: ¿El niño presenta quejido?",
  "e09" = "E9 - OBSERVE: ¿EL NIÑO PRESENTA TIRAJE INTERCOSTAL SEVERO? INDICACIÓN: conteste esta pregunta de lo respondido en C1 ",
  "e10" = "E10 - OBSERVE. ¿El niño presenta cianosis? INDICACIÓN: color azul en la piel alrededor de lengua y boca ",
  "e11" = "E11 - EVALUE: ¿el niño llena los criterios de OMS para tener neumonía severa?  INDICACIÓN: la respuesta es Sí, si el niño llena los criterios de neumonía de OMS (C7=Sí), Y la respuesta a alguna de las preguntas de E1 a E10 es SI ",
  "f01" = "F1. Motivo de la visita:",
  "hora_fin" = "Hora de finalización",
  "c36_gt_41_complete" = "Complete?"
)
